### ISSUE TITLE
video_recv.sh

### ISSUE THREAD

**Issue by alexblack** [squilter/target-land#1]
Hi, looks like a great project, I am interested in the video processing side of things.  I can't find the file `/usr/bin/video_recv.sh` on the controller:

```
root@3dr_controller:/usr/bin# ls vid*
vidlaunch*
root@3dr_controller:/usr/bin#
```

Any ideas? Thanks!

Alex

**Comment by squilter** [comment]
It might have been moved somewhere else.  Maybe try `find | grep vid*` from /

**Comment by djnugent** [comment]
It also may not exist. As of the 2.0 software update solo uses a new video pipeline(gstreamer).

**Comment by squilter** [comment]
Yeah, so maybe try `grep -r "gst-launch"` instead. But then you'll need to figure out how to modify it differently, rather than following the instructions.

**Comment by squilter** [comment]
I figured it out now. No modifications are needed to the solo or the controller software anymore. See the updated readme.
