### ISSUE TITLE
ValueError: too many values to unpack......

### ISSUE THREAD

**Issue by CaptDumpling** [squilter/target-land#2]
Hi I am amazed with what you have done. I just purchased a 3DR Solo not too long ago and wanting to do some programming with it.  I know some C++ programming.  When i ran your code, i got this error.  I am very new to python and just now studying the language.  I am wondering if you could teach me what this error means, i would greatly appreciated.

contours,hierarchy = cv2.findContours(tobecontourdetected,cv2.RETR_LIST,
cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

**Comment by squilter** [comment]
It means that `cv2.findContours` is returning something unexpected. Are you sure that opencv is installed properly?
