### ISSUE TITLE
Process data on companion computer and send only goto command per MAVLink

### ISSUE THREAD

**Issue by maxmlr** [squilter/target-land#3]
Is there anything speaking against doing all processing at the companion computer and just sending a goto command to the vehicle? Thus - in case of the Solo - the firmware on the vehicle itself does not have to be altered.

**Comment by squilter** [comment]
I ran this code on a laptop. It did not require any firmware modifications to the vehicle itself. It should theoretically be possible to run this same code on the solo's companion computer, but it has very limited processing power. Realistically, I think this could probably run well on an odroid.
